### PR TITLE
Update conv.py

### PR DESCRIPTION
**Pull request by indeeo**
lens = (lens - module.kernel_size[0] + 2*module.padding[0] ) / module.stride[0] + 1
第一个卷积块设置了padding值为97，此处应加上 2*module.padding[0]。

### CODE REVIEW

**Comment by nobody132** [comment]
是这样的，已修改。

**Comment by kayzss** [comment]
@seracc  从这里（提取码：xhks）下载预训练模型和测试音频文件，并将它们拷贝到对应位置。
the model and test audio have been removed , would you please share with me ? Thank you in advance !

**Comment by kayzss** [comment]
@indeeo @tbfly  do you have the model and test audio provided by @seracc  and share with me ?
 because 从这里（提取码：xhks）下载预训练模型和测试音频文件 have been removed. Thank you in advance ! My E-mail address: 861186267@qq.com.

**Comment by ylsxw** [comment]
TypeError: paddle_get_scorer(): incompatible function arguments. The following argument types are supported:
    1. (arg0: float, arg1: float, arg2: str, arg3: List[str], arg4: int) -> capsule
运行服务解码器ctcdecode的代码报错了有代替这个的吗

**Pull request closed without merging**
